create web config and create first controller
java-fat-unicorn-team/CarSale pull request #11
Opened 2019-06-27 12:58 UTC by maksimk99

2019-06-27 12:58 UTC, maksimk99 commented
I will add documentation for requests later

2019-06-28 08:58 UTC, maksimk99 reviewed
Add tests: REST and service layer

2019-06-28 08:58 UTC, maksimk99 commented on dao/src/main/java/com/carhouse/dao/impl/CarDaoImpl.java
> +        LOGGER.debug("method getCar with parameter: {} was called", index);
`method getCar with parameter: [{}] was called`

2019-06-28 08:58 UTC, maksimk99 commented on rest/src/main/webapp/index.html
> +<!DOCTYPE html>
should be removed because it's  REST application

2019-06-28 08:58 UTC, maksimk99 commented on service/src/main/java/com/carhouse/service/impl/FuelTypeServiceImpl.java
> + */
`{@see FuelTypeService}`

2019-06-28 08:58 UTC, maksimk99 commented on service/src/main/java/com/carhouse/service/impl/FuelTypeServiceImpl.java
> +    private static final Logger LOGGER = LogManager.getLogger(FuelTypeServiceImpl.class);
replace it before constructor

2019-06-28 11:24 UTC, aleksieiev reviewed
Add tests please

2019-06-28 11:24 UTC, aleksieiev commented on dao/src/test/java/com/carhouse/dao/impl/CarDaoImplTest.java
> +    void addCarCharacteristics() {
rename method

2019-06-28 14:59 UTC, maksimk99 commented
I have one question:
What method of testing rest controllers to choose: Mock or WireMock?
I think Mock is enough for it.

2019-06-28 15:02 UTC, aleksieiev commented
Why do you think so?

2019-06-28 15:54 UTC, maksimk99 commented
I was wrong, WireMock is better
Wiremock provides a simulator for HTTP-based APIs while Mockito provides the mock implementation of the method/object.
When we are using Mockito, we can't test any code to invoke REST service, getting HTTP response and deserializing response. 
It means WireMock is better then Mockito for testing rest controllers.

2019-06-28 16:14 UTC, aleksieiev commented
By the way, what are we going to test?

2019-07-02 11:37 UTC, maksimk99 commented
I've deleted some endpoints.
I will change the database structure for carCharacteristic model and add more changes to endpoints,
but it will be another issue

2019-07-04 12:59 UTC, maksimk99 commented
I've opened an issue to choose a way of testing REST controllers
see `#12`

2019-07-04 13:12 UTC, aleksieiev commented
https://github.com/java-fat-unicorn-team/CarSale/issues/12
MockMVC has been chosen

2019-07-04 13:13 UTC, aleksieiev requested changes
No changes has been found.

2019-07-05 07:04 UTC, aleksieiev reviewed
Great :-)
Does this PR require anything additional? I remember something about service tests.

2019-07-05 08:23 UTC, maksimk99 commented
I've added these tests before.
I have one question: if I've removed add, update and delete endpoints for FuelType model, should I remove these operations from DAO layer?

2019-07-05 08:31 UTC, aleksieiev commented
How do you think?

2019-07-05 08:35 UTC, maksimk99 commented
remove

2019-07-05 08:38 UTC, aleksieiev commented
So. be brave and remove them if it isn't required.

2019-07-05 09:22 UTC, aleksieiev approved these changes

2019-07-05 09:22 UTC, aleksieiev commented on service/src/main/test/java/com/carhouse/service/impl/FuelTypeServiceImplTest.java
> +        listFuelTypes = new ArrayList<>(){{
can be replaced to 
` private List<FuelType> listFuelTypes = new ArrayList<>(){{ ... }};`

2019-07-05 09:22 UTC, aleksieiev commented on service/src/main/test/java/com/carhouse/service/impl/FuelTypeServiceImplTest.java
> +        listFuelTypes = new ArrayList<>() {{
can be moved to `private` initialization

2019-07-05 09:23 UTC, merged